#SFTP Configuration
sftp:
  host: "us-east-1.sftpcloud.io"
  port: "22"
  
#Email SMTP Configuration
email:
  host: "smtp.gmail.com"
  port: "587"
  
#Object Store Configuration
os:
  maxEntries: "100000"
  entryTtl: "6"
  expirationInterval: "4"
  
#HTTP Configuration
http:
  host: "0.0.0.0"
  port: "8081"